# Generated by Django 2.2.5 on 2019-09-17 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='openQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.TextField(verbose_name='Q')),
            ],
        ),
        migrations.CreateModel(
            name='openQ_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField(max_length=1000, verbose_name='回答')),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('openQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mypage.openQ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implessions', models.CharField(blank=True, max_length=60, verbose_name='団体名')),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
