# Generated by Django 2.2.5 on 2019-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.TextField(max_length=200, null=True, verbose_name='自己紹介'),
        ),
    ]
