# Generated by Django 2.2.5 on 2019-09-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='質問')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('status', models.CharField(choices=[('1', '回答待ち'), ('2', '回答済'), ('3', '非表示')], max_length=1, verbose_name='ステータス')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerer', to=settings.AUTH_USER_MODEL)),
                ('questionner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
