# Generated by Django 2.2.5 on 2019-10-02 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionBoxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('1', '回答待ち'), ('2', '回答済'), ('3', '非表示')], default=1, max_length=1, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.ManyToManyField(to='questionBoxes.QIndex'),
        ),
    ]
