# Generated by Django 2.2.5 on 2019-10-02 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionBoxes', '0002_auto_20191002_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(verbose_name='回答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答日')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionBoxes.Question')),
            ],
        ),
    ]
