# Generated by Django 2.2.5 on 2019-09-25 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addexchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressexchange',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AlterField(
            model_name='addressexchange',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申請日時'),
        ),
    ]
